version: 2

jobs:
  build:
    machine: true

    environment:
      CI_SCRIPTS_BRANCH: master

    steps:

      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}-v1

      - run:
          name: Build
          command: ./mvnw -B install -Dmaven.test.skip=true

      - run: git clone -b $CI_SCRIPTS_BRANCH git@github.com:ClouDesire/ci-scripts.git

      - run:
          name: Run Sonar
          command: |
            source ci-scripts/sonar.sh
            run_sonar

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}-v2
          paths:
            - "~/.m2"
            - "~/.sonar/cache"

      - run:
          name: Deploy artifacts
          command: if [ "$CIRCLE_BRANCH" == "master" ]; then ./mvnw -B deploy -Dmaven.test.skip=true; fi
