version: 2

jobs:
  build:
    machine: true

    steps:

      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}-v1

      - run:
          name: Build
          command: ./mvnw -B install -Dmaven.test.skip=true

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}-v2
          paths:
            - "~/.m2"
            - "~/.sonar/cache"

      - run:
          name: Deploy artifacts
          command: if [ "$CIRCLE_BRANCH" == "master" ]; then ./mvnw -B deploy -Dmaven.test.skip=true; fi
